# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

# - task: NuGetToolInstaller@1
#   inputs:
#     versionSpec: 4.1.1
#     checkLatest: true

# - task: NuGetCommand@2
#   inputs:
#     command: 'restore'
#     restoreSolution: '**/*.sln'
#     feedsToUse: 'config'
#     externalFeedCredentials: '6880d827-fec6-430c-b44b-e8466757dbe2'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '3.0.100'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
  
  
# - task: NuGetCommand@2
#   inputs:
#     command: 'pack'
#     packagesToPack: '**/*.csproj'
#     versioningScheme: 'byBuildNumber'

- task: NuGetCommand@2
  inputs:
    command: 'push'
    feedsToUse: 'config'
    externalFeedCredentials: 'DevMaid'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'DevMaid'
